### DISCUSSION TITLE
Hot water useage tracker

### DISCUSSION THREAD

**Discussion by DirkFace** [tomasmcguinness/homeassistant-mixergy#10] [Ideas]
This is a work in progress, so feel free to make alterations & suggestions to what I have done so far if you choose to use it.

Basically I wanted to add a daily water useage into my Home assistant energy dashboard, but as the only part I can easily track is the hot water from the mixergy tank I decided to tackle that & ignore the cold water for now.

The obvious sensor to utilise is the 'percentage available', but as that declines over time as the water cools & then also rises when being heated - it needed a little more thought.

I noticed that my water naturaly lost 0.1% over a short period as it cooled (with a variance).
So I monitored the drop to only register when it was 0.2% over 60 seconds using the TREND sensor.
I also use the DERIVATIVE sensor to do a similar function over a 15 minute period.
The 2 STATISTICS sensors monitor a minumum & maximum percentage over a period of 20 minutes, which I use to calculate a ballpark figure of the percentage used once the derivative or trend sensor activate.

The litres sensor basically converts the percentage used into litres, depending on the tank size (mine is 120L). This is also the sensor that will be recognised by the energy dashboard.

At present this is my sensors in YAML :

```
# Derivative to determin if hot water has been used

  - platform: derivative
    source: sensor.current_charge
    name: Hot water used
    round: 1
    unit_time: min 
    time_window: "00:15:00"

# Statistics to determin min / max over 20 mins
    
  - platform: statistics
    name: "Water val min"
    unique_id: water_val_min
    entity_id: sensor.current_charge
    state_characteristic: value_min
    max_age:
      minutes: 20
    sampling_size: 40
    precision: 1
    
  - platform: statistics
    name: "Water val max"
    unique_id: water_val_max
    entity_id: sensor.current_charge
    state_characteristic: value_max
    max_age:
      minutes: 20
    sampling_size: 40
    precision: 1

# Calculate Water in Litres (tank is size of mixergy tank in litres)

template:
  - sensor:
      - name: "Litres"
        unique_id: "litres"
        icon: hass:cup-water
        device_class: water
        unit_of_measurement: "L"
        state_class: total_increasing
        state: >
          {% set tank = 120 | float(0) / 100 %}
          {% set litres = ((states('input_number.water_used') | float(0) * tank ) | float(0)) | round(2) %}
          {{ litres }}
        
# Water increasing /  decreasing

binary_sensor:
  - platform: trend
    sensors:
      water_falling:
        entity_id: sensor.current_charge
        sample_duration: 180
        max_samples: 6
        min_gradient: -0.003333
        device_class: battery

      water_rising:
        entity_id: sensor.current_charge
        sample_duration: 180
        max_samples: 6
        min_gradient: 0.001666
        device_class: battery_charging
```
I created 2 HELPERS called 'Water top' & 'Water used' - both are NUMBER helpers.
These are used in an automation to assist with the calculation when water useage has been detected ...

```
alias: Water being used calculation
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.water_falling
    to: "on"
    from: "off"
  - platform: numeric_state
    entity_id: sensor.hot_water_used
    below: 0
condition: []
action:
  - service: input_number.set_value
    data:
      value: "{{ states('sensor.water_val_max') }}"
    target:
      entity_id: input_number.water_top
  - wait_for_trigger:
      - platform: state
        entity_id:
          - binary_sensor.water_falling
        from: "on"
        to: "off"
    timeout:
      hours: 0
      minutes: 15
      seconds: 0
      milliseconds: 0
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.water_rising
            state: "off"
            for:
              hours: 0
              minutes: 2
              seconds: 0
        sequence:
          - service: input_number.set_value
            data:
              value: >-
                {% set a = states('input_number.water_top') | round(1) %} {% set
                b = states('sensor.water_val_min') | round(1) %} {% set c =
                states('input_number.water_used') | round(1) %} {% set d =
                c+(a-b) | round(1) %} {{ d }}
            target:
              entity_id: input_number.water_used
    default:
      - service: input_number.set_value
        data:
          value: >-
            {% set a = states('input_number.water_top') | round(1) %} {% set b =
            states('sensor.current_charge') | round(1) %} {% set c =
            states('input_number.water_used') | round(1) %} {% set d = c+(a-b) |
            round(1) %} {{ d }}
        target:
          entity_id: input_number.water_used
mode: single
```

I also needed to reset the daily useage after midnight ...

```
alias: Reset water used
description: ""
trigger:
  - platform: time
    at: "00:01:00"
condition: []
action:
  - service: input_number.set_value
    data:
      value: 0
    target:
      entity_id: input_number.water_used
mode: single
```

This is what it looks like on my Dashboards.

![HA](https://user-images.githubusercontent.com/25860884/229850848-6fd306db-121c-45a0-a96f-cc2cbe53a69c.jpg)

![Water](https://user-images.githubusercontent.com/25860884/229850954-1b8d03c9-ea5e-4b66-8383-4b5e97c29bdc.png)
