### DISCUSSION TITLE
Automations: When hot water low - Boost tank

### DISCUSSION THREAD

**Discussion by dcw77** [tomasmcguinness/homeassistant-mixergy#28] [Ideas]
It would be great if you could action a boost from the integration as you can from the Mixergy app. So if your low hot water sensor activated then it could action a boost to whatever your desired percentage

**Comment by DirkFace** [comment]
You can already. Use the hot water available entity to check required level, then call a service to boost the tank.

**Reply by dcw77** [reply]
Is this a service you've configured yourself to the mixergy api as there are no actions included with is Integration?

**Reply by DirkFace** [reply]
No it's all in there already.

Here's a simple automation that should work -

```
alias: Mixergy - Hot water is low
description: if hot water is low then notify user and top up tank to 40%
trigger:
  - platform: numeric_state
    entity_id:
      - sensor.current_charge
    below: 10
action:
  - service: notify.notify
    data:
      message: Hot water is at 10% !!
      data:
        push:
          interruption-level: critical
          volume: 1
      title: Warning
  - service: mixergy.mixergy_set_charge
    data:
      charge: 40
mode: single
```
